// This file is automatically generated. Do not edit it directly.
// NOTA: Este arquivo não está mais sendo usado. O projeto foi migrado para usar dados mockados.
// Para reconectar ao banco de dados no futuro, descomente o código abaixo e atualize os hooks.

/*
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
*/

// Placeholder para evitar erros de importação
export const supabase = null as any;